name: Unit Tests # name of the test

on:
  push:
    branches: [StarterCodeDrafts, testing]  
  pull_request:
    branches: [StarterCodeDrafts, testing] 

jobs:
  tests: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm install 
      - name: Unit Test
        run: npm test 
